user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

blog:
    resource: "@BlogBundle/Controller/"
    type: annotation
app:
    resource: '@AppBundle/Controller/'
    type: annotation