<?php

namespace BlogBundle\Repository;
use BlogBundle\Entity\Post;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function save(Post $post)
    {
        $em = $this->getEntityManager();
        $em->persist($post);
        $em->flush();
        return $post->getId();
    }
    /**
     * @param $author
     * @param \DateTime $date
     * @return array
     */
    public function findPostByAuthorAndDate($author, \DateTime $date)
    {
        $queryBuilder = $this->createQueryBuilder('p')
            ->where('p.author = :author')
            ->andWhere('p.createdAt >= :date')
            ->orderBy('p.title', 'ASC')
            ->setParameter('author', $author)
            ->setParameter('date', $date)
            ->getQuery();
        $result = $queryBuilder->getResult();
        return $result;
    }
}
